# Adapted from:
# - https://github.com/dependabot/fetch-metadata#enabling-auto-merge
# - https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request

name: Dependabot auto-merge
on:
  workflow_call:
    secrets:
      personal-access-token:
        required: true

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    # Checking the workflow triggerer will prevent the workflow run failing on non-Dependabot commits and PRs. Checking
    # the PR author isn't sufficient since it might be necessary to push commits to a Dependabot PR. In that case, it's
    # best to skip running this workflow since the original Dependabot PR has been edited and it might be reasonable to
    # do a manual merge of the Dependabot PR with the custom changes. Running this workflow for other than Dependabot's
    # commits would also require adding the given personal access token secret to the action's secrets instead of the
    # Dependabot secrets.
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1
      - name: Enable auto-merge for Dependabot PR
        # Only merge minor and patch versions
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor' || steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.personal-access-token }}
